baseURL = "https://genegi.github.io/"
languageCode = "en-us"
title = "Gene Gi's Blog"
theme = "ananke"
publishDir = "docs"

[params]
  author = "Gene Gi"
  description = "Thoughts, ideas, and projects"
  github = "https://github.com/GeneGi"
  favicon = ""
  site_logo = ""
  background_color_class = "bg-black"
  recent_posts_number = 5
